### ISSUE TITLE
Server atomic counter is likely not aligned correctly on 32bit systems

### ISSUE THREAD

**Issue by iaburton** [VerticalOps/golang-socketio#5]
While reading some docs recently I was reminded of an issue I've known about for some time, and has existed in Go for some time, but isn't something you run into often.

https://github.com/golang/go/issues/599
https://golang.org/pkg/sync/atomic/#pkg-note-BUG

This issue is about the last BUG listed in the atomic package. If this package is to be used on those architectures then the count field in the Server may need to be moved. Or more research should be done if storing the count via pointer and not value is good enough.
https://github.com/VerticalOps/golang-socketio/blob/99320d63cf4aca76a555da57b2a052440550c402/server.go#L57

**Comment by langbeck** [comment]
This isn't an issue since they are pointing to an "allocated" memory:
https://github.com/VerticalOps/golang-socketio/blob/99320d63cf4aca76a555da57b2a052440550c402/server.go#L410
From your own reference: `The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned.`

**Comment by langbeck** [comment]
But there still room for improvement. If we change `count *int64` to `count int64` and move its definition to the beginning of the `Server` struct.

After that, just replace the following block
https://github.com/VerticalOps/golang-socketio/blob/99320d63cf4aca76a555da57b2a052440550c402/server.go#L401-L412
with
```golang
srv := new(Server) 
srv.initMethods() 
srv.tr = tr 
srv.channels = make(map[string]map[*Channel]struct{}) 
srv.rooms = make(map[*Channel]map[string]struct{}) 
srv.sids = make(map[string]*Channel) 
srv.onConnection = onConnectStore 
srv.onDisconnection = onDisconnectCleanup 
srv.done = make(chan struct{}) 
srv.count = new(int64) 
```

**Comment by iaburton** [comment]
> This isn't an issue since they are pointing to an "allocated" memory:
> https://github.com/VerticalOps/golang-socketio/blob/99320d63cf4aca76a555da57b2a052440550c402/server.go#L410
> 
> 
> From your own reference: `The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned.`

Correct, I wasn't actually sure if it was even needed
> ...the count field in the Server _may_ need to be moved. Or more research should be done if storing the count via pointer and not value is good enough.

That said, the existing code and your suggestion work (though you'd have to remove `srv.count = new(int64)` if it was no longer a pointer) fine. To be honest I've made the minimum changes we needed from this package but it can still use help (I also only changed the server type, we don't use the client, and the readme is outdated). Are you looking to use it @langbeck ? Because a potential problem is that the import paths are incorrect, it contains `verticalops` instead of `VerticalOps`, so vendoring it might be an issue.

**Comment by langbeck** [comment]
@iaburton I'm not going to use this package, no worries.
I was just Googling about Go memory layout and came across this issue and thought I could help. =)

**Comment by iaburton** [comment]
@langbeck ah okay no problem. That's actually kinda surprising this would show up in such search results haha this issue was mostly to serve as a reminder for me if it ever came up. I'll go ahead and close it, thanks.
